//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Menu
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Type { get; set; }
        public string Structure { get; set; }
        public string Photo { get; set; }
        public string Vegetarian { get; set; }
    }

    public class MenuListViewModel
    {
        public IEnumerable<Menu> Menus { get; set; }
        public SelectList Price { get; set; }
        public SelectList Vegetarian { get; set; }
    }
}
